CREATE TABLE IF NOT EXISTS `order_review` (
  `id` bigint NOT NULL COMMENT 'primary key',
  `order_id` bigint NOT NULL COMMENT 'order id',
  `order_detail_id` bigint NOT NULL COMMENT 'order detail id',
  `user_id` bigint NOT NULL COMMENT 'review user id',
  `dish_id` bigint DEFAULT NULL COMMENT 'dish id',
  `setmeal_id` bigint DEFAULT NULL COMMENT 'setmeal id',
  `item_name` varchar(100) DEFAULT NULL COMMENT 'dish or setmeal name',
  `rating` int NOT NULL COMMENT '1-5 rating',
  `content` varchar(1000) DEFAULT NULL COMMENT 'review content',
  `image` varchar(500) DEFAULT NULL COMMENT 'review image list',
  `is_anonymous` tinyint NOT NULL DEFAULT 0 COMMENT '0 no, 1 yes',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '0 hidden, 1 visible',
  `reply` varchar(1000) DEFAULT NULL COMMENT 'merchant reply',
  `reply_time` datetime DEFAULT NULL COMMENT 'reply time',
  `reply_user` bigint DEFAULT NULL COMMENT 'reply employee id',
  `create_time` datetime DEFAULT NULL COMMENT 'create time',
  `update_time` datetime DEFAULT NULL COMMENT 'update time',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_review_detail_user` (`order_detail_id`, `user_id`),
  KEY `idx_order_review_order` (`order_id`),
  KEY `idx_order_review_user` (`user_id`),
  KEY `idx_order_review_rating` (`rating`),
  KEY `idx_order_review_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='order review';

CREATE TABLE IF NOT EXISTS `order_after_sale` (
  `id` bigint NOT NULL COMMENT 'primary key',
  `order_id` bigint NOT NULL COMMENT 'order id',
  `user_id` bigint NOT NULL COMMENT 'apply user id',
  `type` tinyint NOT NULL COMMENT '1 refund, 2 compensation',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '1 pending, 2 approved, 3 rejected, 4 completed',
  `reason` varchar(200) NOT NULL COMMENT 'apply reason',
  `description` varchar(1000) DEFAULT NULL COMMENT 'apply description',
  `evidence` varchar(500) DEFAULT NULL COMMENT 'evidence image list',
  `apply_amount` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT 'requested amount',
  `handle_amount` decimal(10,2) DEFAULT NULL COMMENT 'approved refund or compensation amount',
  `handle_remark` varchar(1000) DEFAULT NULL COMMENT 'handle remark',
  `apply_time` datetime NOT NULL COMMENT 'apply time',
  `handle_time` datetime DEFAULT NULL COMMENT 'handle time',
  `handle_user` bigint DEFAULT NULL COMMENT 'handle employee id',
  `create_time` datetime DEFAULT NULL COMMENT 'create time',
  `update_time` datetime DEFAULT NULL COMMENT 'update time',
  PRIMARY KEY (`id`),
  KEY `idx_after_sale_order` (`order_id`),
  KEY `idx_after_sale_user` (`user_id`),
  KEY `idx_after_sale_status` (`status`),
  KEY `idx_after_sale_apply_time` (`apply_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='order after sale';
